- name: MySql server setup
  hosts: localhost
  become: yes
  tasks: 
   - name: Install mysql
     ansible.builtin.dnf:
      name: mysql-server
      state: latest
   
   - name: Start MySQL Service
     ansible.builtin.systemd_service:
      name: mysql-server
      state: start
      enabled: yes 

   - name: Setup MySQL password
     ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1