- name: Demo on Template
  hosts: localhost
  tasks:
   - name: Copy example.conf
     ansible.builtin.copy:
      src: example.conf
      dest: /tmp/example-copy.conf

   - name: Printing using template module 
     ansible.builtin.template:
      src: example.conf
      dest: /tmp/example-template.conf