- name: Frontend App
  hosts: all
  become: yes
  roles:
   - frontend





    #  To run a role 
    # ansible-playbook -i 172.31.86.215, -e ansible_user=ec2-user -e ansible_password=DevOps321 frontend.yml
    #  172.31.86.215 is the private ip address of the front end  server