 - name: Install mysql
   ansible.builtin.dnf:
    name: mysql-server
    state: latest
  
 - name: Start MySQL Service
   ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes 

 - name: Setup MySQL password
   ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ mysql_root_password }}